package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"strings"
)

// create type called 'deck'
// which is slice of strings
// why we add type?
//     if we want to create a function based on
//     the type and what its belong
type deck []string

// why this functions its not added some receiver?
// because the purposes is for declaring a new deck
// it just a simple code that initialize a new deck
func newDeck() deck {
	cards := deck{}

	cardSuits := []string{"Spades", "Hearts", "Clubs", "Diamonds"}
	cardValues := []string{
		"Two", "Three", "Four", "Five",
		"Six", "Seven", "Eight", "Nine", "Ten",
		"Jack", "Queen", "King", "Ace",
	}

	for _, suits := range cardSuits {
		for _, values := range cardValues {
			cards = append(cards, values+" of "+suits)
		}
	}

	return cards
}

// this function below has a weird naming
// (d deck) is a 'receiver' for the function
// which generated by declaring a new deck
//    cards := deck{"3 of Hearts", "5 of Spades"}
// the deck type were implementing a single memory
func (d deck) print() {
	for i, card := range d {
		fmt.Println(i, card)
	}
}

// what the heck with the return values?
// it just a multiple return values of types
// both of return value is the type of deck
// first return value will taken by first variable
// which call the function. And so forth
func deal(d deck, handSize int) (deck, deck) {
	return d[:handSize], d[handSize:]
}

func (d deck) toString() string {
	return strings.Join([]string(d), ",")
}

func (d deck) saveToFile(filename string) error {
	return ioutil.WriteFile(filename, []byte(d.toString()), 0666)
}

func newDeckFromFile(filename string) deck {
	byteSlices, err := ioutil.ReadFile(filename)
	if err != nil {
		fmt.Println("Error: ", err)
		os.Exit(1)
	}

	str := strings.Split(string(byteSlices), ",")
	return deck(str)
}
