package main

import "fmt"

// create type called 'deck'
// which is slice of strings
// why we add type?
//     if we want to create a function based on
//     the type and what its belong
type deck []string

// this function below has a weird naming
// (d deck) is a 'receiver' for the function
// which generated by declaring a new deck
//    cards := deck{"3 of Hearts", "5 of Spades"}
// the deck type were implementing a single memory
func (d deck) print() {
	for i, card := range d {
		fmt.Println(i, card)
	}
}
